trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- script: mkdir fldatesting.com
  displayName: 'Create Website Folder'

- script: echo ^<html^>^<body^>^<h1^>testing website^</h1^>^</body^>^</html^> > fldatesting.com\index.html
  displayName: 'Create index.html'

- script: type fldatesting.com\index.html
  displayName: 'Show File Content'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'fldatesting.com'
    ArtifactName: 'fldatesting-site'